<?php
/** @var array $url */
?>

<div class="mt-6 px-8">
  <h1 class="text-4xl">
    Сайт: <?= htmlspecialchars($url['name']) ?>
  </h1>

  <table data-test="url" class="mt-4 w-full border-collapse border border-stone-300">
    <tbody>
      <tr class="hover:bg-stone-200">
        <td class="border border-stone-300 px-4 py-2 font-medium">ID</td>
        <td class="border border-stone-300 px-4 py-2"><?= $url['id'] ?></td>
      </tr>
      <tr class="hover:bg-stone-200">
        <td class="border border-stone-300 px-4 py-2 font-medium">Имя</td>
        <td class="border border-stone-300 px-4 py-2"><?= htmlspecialchars($url['name']) ?></td>
      </tr>
      <tr class="hover:bg-stone-200">
        <td class="border border-stone-300 px-4 py-2 font-medium">Дата создания</td>
        <td class="border border-stone-300 px-4 py-2"><?= $url['createdAt'] ?></td>
      </tr>
    </tbody>
  </table>
</div>