<form action="/urls" method="post" class="mx-auto w-fit bg-stone-100 border border-stone-300 rounded-md p-8 mt-4">
    <h1 class="text-5xl">Анализатор страниц</h1>
    <p class="mt-4 text-sm">Бесплатно проверяйте сайты на SEO-пригодность</p>
    
    <div class="mt-4 flex w-full gap-4">
      <input 
        class="flex-1 rounded-md border border-gray-300 px-3 py-2"
        type="text" 
        name="url" 
        placeholder="https://www.example.com"
      >
      <button 
        class="rounded-md bg-blue-600 px-10 py-2 font-medium text-white uppercase"
        type="submit"
      >
        Проверить
      </button>
    </div>
</form>